#!/usr/bin/env python3
"""Stage-level status for a stage review -- rendered for three different readers.

WHY THIS EXISTS SEPARATELY FROM dag.py's OWN PAGE.

dag.py renders an engineer's board: every node, every container, one row each.
That is the right shape for the person on call and the wrong shape for a stage
review. "Grafana 檢視 — running" tells a reviewer nothing they can act on; it is
tool status, not stage status.

So this reorganises the SAME live probes into the unit a reviewer thinks in --
the STAGE -- and pairs each line with its architecture and flow diagram. A stage
is green only if every node under it is green, and it names which node is
responsible when it is not. Nothing here is hand-written status: every light
comes from dag.build(), which queries the database and the cluster at the moment
this runs.

THREE READERS, THREE RENDERINGS, ONE MODEL.

The failure this file is built against: one artifact serving three audiences
serves none of them. So stage_model() is the single source of truth and there
are three renderers over it, each shaped by what its reader actually does next.

  html  人類 / 長官 -- lights, diagrams, and A DECISION LIST SEPARATED FROM THE
        ENGINEERING LIST. A flat amber list makes a reviewer read nineteen rows
        to find the one that is waiting on them. That is the difference between
        a report that gets acted on and one that gets skimmed.
  json  machine -- schema-versioned, complete, stable key names. For anything
        that wants to assert on the state rather than look at it.
  md    AI / chat -- a few KB, non-green stages expanded and green ones rolled
        up to one line. An 80 KB HTML page with six inlined SVGs is not an
        input; it is a denial-of-service on a context window.

WHY IT IS GENERATED RATHER THAN WRITTEN.

A written status document is accurate on the day it is written and misleading
from the next. This one is regenerated by the scheduler, and every rendering
carries the timestamp it was generated at, so a stale copy announces itself.

Usage:
  stage_report.py                  # all three formats into docs/
  stage_report.py --format md      # just the digest, to stdout
  stage_report.py --selfcheck      # validate the hand-written metadata
"""
from __future__ import annotations

import argparse
import html
import importlib.util
import json
import os
import re
import sys
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
DOCS = os.path.join(REPO_ROOT, "docs")
SCHEMA = "stage-report/1"

_spec = importlib.util.spec_from_file_location("dag", os.path.join(HERE, "dag.py"))
dag = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(dag)


# --------------------------------------------------------------------------
# Stage map. Nodes are grouped into the stages a reviewer asks about.
#
# The grouping is not cosmetic: it decides what a single light means. Four
# separate rows saying "Prometheus running / Loki running / Grafana running /
# Alertmanager no alerts" answer "which containers are up". One row saying
# "觀測" answers "can we see what the platform is doing", which is the question
# actually being asked.
# --------------------------------------------------------------------------

def stage(name, nodes, why):
    return {"name": name, "nodes": nodes, "why": why}


LINES = [
    ("devops", "DevOps", "交付與維運", [
        stage("基礎", ["vault", "audit", "scheduler", "certs", "rotation", "iac"],
              "機密、身分、稽核軌跡與排程器——其他每一段都站在這上面"),
        stage("原始碼閘門", ["sast", "secrets"],
              "進建置之前擋下：原始碼弱點與歷史中的秘密"),
        stage("建置與映像", ["ci", "gha", "trivy", "registry"],
              "編譯、遠端 CI、映像漏洞掃描、推送到 registry"),
        # prodk8s is the SECOND MACHINE (ADR-0008), on the same stage as the
        # lab cluster rather than a stage of its own: they are the same step of
        # the pipeline, executed on different hardware. Added here the same day
        # the dag node was, because a node that exists in dag.py and not in
        # LINES is invisible on this report -- and invisible reads identically
        # to healthy. The selfcheck refuses to render until they agree, which
        # is how this omission was caught within the hour.
        stage("部署", ["k8s", "bluegreen", "prodk8s", "develop"],
              "Kubernetes 底座與藍綠切換（切換是改 Service 指向，不是滾動更新）"),
        stage("驗證", ["dast", "llmreview"],
              "對執行中的系統掃描，以及模型複審"),
        stage("人工關卡", ["gate"],
              "上 production-like 需要真人按下去，刻意不自動"),
        stage("上線", ["prodlike", "nginx"],
              "對外服務與入口"),
        stage("觀測", ["prometheus", "loki", "alertmgr", "grafana"],
              "指標、日誌、告警、檢視——平台能不能看見自己"),
        stage("備份與還原", ["backup", "restore"],
              "備份覆蓋率不得有漏；沒還原過的備份不算備份"),
        stage("主機資源", ["hostdisk", "prodhost"],
              "兩台機器各自的磁碟與節點壓力。分開兩個節點是刻意的——"
              "一個節點蓋兩台，任一台回答就會變綠"),
    ]),
    ("dataops", "DataOps", "資料工程", [
        stage("來源與權威", ["sources", "srcfresh", "geo"],
              "來源以列舉發現而非猜 URL；地理對照每筆帶證據"),
        stage("載入", ["facts"],
              "同一張事實表容納縣市×週、鄉鎮×年、鄉鎮×日"),
        stage("血緣", ["lineage"],
              "檔案列數 = 接受 + 拒絕 + 重複，是資料庫約束不是報表"),
        stage("契約", ["dcontract"],
              "資料契約進 CI；資料庫缺席時失敗而不是跳過"),
        stage("時間軸對照", ["epiweek"],
              "流行病學週要對得上日曆日，週資料與日資料才能結合"),
    ]),
    ("mlops", "MLOps", "模型維運", [
        stage("特徵", ["features"],
              "特徵集綁定產生它的程式碼雜湊"),
        stage("回測", ["backtest"],
              "rolling-origin，與兩個天真基準在同一批折上評分"),
        stage("上線閘門", ["mgate"],
              "輸了不准上線，是資料庫觸發器不是團隊慣例"),
        stage("發布", ["forecast"],
              "API 只做查詢，服務路徑不載入模型"),
        stage("事後評分", ["fcscore"],
              "拿發出去的那個數字比真的到來的那一週；回測比的是模型被擬合圍繞的歷史，不是這件事"),
        stage("重訓", ["retrain"],
              "每週排程；日曆觸發已實測，不是手動跑過就算"),
    ]),
]


# --------------------------------------------------------------------------
# ASKS -- the only hand-written judgement in this file, and it is deliberately
# built so that it cannot go stale silently.
#
# The problem being solved: an amber list that mixes "engineering is on it"
# with "this is waiting on a decision only you can make" forces the reviewer to
# read every row to find the one that is theirs. Grouping by WHO OWNS THE NEXT
# MOVE is the difference between a list that gets acted on and one that gets
# skimmed.
#
# The rot hazard is obvious: a hand-written note attached to a stage stays
# attached after the reason for it is gone, and then the page is confidently
# wrong. Two mechanisms against that, and they matter more than the text:
#
#   1. An ask is BOUND TO A LIVE CONDITION -- a node id plus a substring that
#      must appear in that node's CURRENT detail. It renders only while the
#      platform is actually reporting that condition. It cannot outlive it.
#   2. --selfcheck reports asks matching nothing, so a resolved one surfaces as
#      a deletion candidate instead of sitting there forever.
#
# `owner` is who makes the next move, not who is to blame:
#   decision  waiting on the platform owner to choose. Engineering cannot
#             proceed by working harder.
#   external  waiting on an outside body. Not ours to schedule.
#   research  an open research result, not a defect. "Fixing" it is a category
#             error -- the honest report is that the model lost.
# Anything non-green with NO matching ask is `eng` by default: nobody is being
# asked for anything, engineering owns it.
# --------------------------------------------------------------------------

ASKS = [
    {
        "id": "offsite-destination",
        "node": "scheduler",
        "when": "not configured: offsite",
        "owner": "decision",
        "ask": "異地備份沒有目的地。備份目前只存在這台筆電上——筆電遺失等於備份一起遺失。",
        "options": [
            "選一個目的地（NAS / 物件儲存 / 另一台機器）並設定 sync_remote.sh",
            "明確記錄「此階段不做異地備份」及理由，讓它變成已知風險而不是紅燈",
        ],
        "ref": "docs/Backlog.md",
    },
    {
        "id": "prod-workload-reachability",
        "node": "prodk8s",
        "when": "沒有任何工作負載",
        "owner": "decision",
        # RECLASSIFIED 2026-09-10, from eng. It sat in eng because "deploy the
        # pilot to ubu" sounds like engineering. It was measured that day and
        # it is not: the amd64 image exists in ghcr (pilot-image.yml builds it
        # natively, verified 09-09), and the ghcr token is in Vault, so the
        # image half is done. The manifest points the pod at
        # host.k3d.internal:18200 (Vault) and :15432 (Postgres), and BOTH are
        # bound to 127.0.0.1 on the Mac -- confirmed from ubu, connection
        # refused on both. There is no amount of engineering that gets past
        # that without someone deciding to open them, or to run a second Vault.
        "ask": "prod 叢集有一個 amd64 映像可以跑，但 pod 需要的 Vault 與資料庫都只綁在 "
               "Mac 的 127.0.0.1 上（從 ubu 實測 connection refused）。"
               "這不是工程問題，是要不要把它們開出去的問題。",
        "options": [
            "把 Vault 與 Postgres 開到區網（只給 ubu），沿用現有那一套動態憑證——"
            "改動最小，但擴大了曝險面，而曝險範圍是您定的",
            "在 ubu 上另起一套 Vault ＋ 資料庫（Backlog T7）——隔離最乾淨，"
            "但會產生第二組 unseal key，而那組鑰匙放哪裡只有您能決定",
            "明確記錄「prod 叢集此階段只證明它會回應，不承載服務」，讓黃燈變成已知狀態",
        ],
        "ref": "docs/Backlog.md",
    },
    {
        "id": "llm-review-artifacts",
        "node": "llmreview",
        "when": "已退役的 Compose 路徑",
        "owner": "decision",
        # Also reclassified from eng, and for a derived reason: T30 says the
        # work is "decide the shape of the Kubernetes artefact". That artefact
        # does not exist until something is deployed to prod, which is the
        # question above. Leaving it as eng implied someone could just go and
        # do it.
        "ask": "LLM 複審的輸入來自已退役的 Compose 路徑。要接回去得先有 Kubernetes 產物，"
               "而那要等上面那個決定。",
        "options": [
            "先回答 prodk8s 那一題；這一項會跟著解開",
            "或明確記錄「LLM 複審此階段不接回」，讓它從待辦變成已知取捨",
        ],
        "ref": "docs/Backlog.md",
    },
    {
        "id": "smtp-credential",
        "node": "alertmgr",
        # Matched on the channel name, not just "沒接上": if telegram ever comes
        # unwired too, that is an engineering fault and must NOT be absorbed
        # into a question addressed to the user.
        "when": "沒接上: email",
        "owner": "decision",
        "ask": "郵件通道從未接上：Vault 裡沒有 secret/devops/smtp 這一筆，"
               "而 platform/notify/setup_mail.sh 讀的就是它。程式沒有壞，是那筆機密"
               "從來沒有被建立，只有帳號持有人拿得到。"
               "代價是實測過的——2026-09-07 到 09-10 Telegram 有三天送不出去，"
               "而那三天沒有第二條通道可以退。",
        "options": [
            "取得一組 SMTP 帳號與 app password，寫進 Vault 的 secret/devops/smtp，"
            "再跑 platform/notify/setup_mail.sh <address>（它會先實際寄一封才宣稱可用）",
            "明確記錄「只用單一通道」及理由，讓它變成已知風險而不是待辦",
        ],
        "ref": "docs/Runbook.md",
    },
    {
        "id": "epiweek-definition",
        "node": "epiweek",
        "when": "無日曆日",
        "owner": "external",
        "ask": "流行病學週對不上日曆日。週資料與日資料無法結合，中醫大個人級資料也接不進來。",
        "options": [
            "向疾管署確認週界定義（起訖日、跨年週歸屬）——只有他們能給權威答案",
        ],
        "ref": "docs/Backlog.md",
    },
    {
        "id": "model-loses-to-persistence",
        "node": "mgate",
        "when": "持平基準",
        "owner": "research",
        "ask": "模型在 rolling-origin 回測輸給「持平」天真基準。上線閘門因此擋住發布——閘門運作正常，這不是缺陷。",
        "options": [
            "維持擋住。誠實的研究結果不該被繞過",
            "突破口是個體級資料（中醫大），不是再調參數",
        ],
        "ref": "docs/Backlog.md",
    },
]

OWNER_LABEL = {
    "decision": "待您決定",
    "external": "外部單位",
    "research": "研究議題",
    "eng": "工程自理",
}
OWNER_ORDER = ["decision", "external", "research", "eng"]

STATE_ORDER = {dag.OK: 0, dag.SUPERSEDED: 1, dag.WARN: 2, dag.UNKNOWN: 3, dag.FAIL: 4}
STATE_LABEL = {dag.OK: "正常", dag.SUPERSEDED: "已被取代", dag.WARN: "注意",
               dag.UNKNOWN: "無法判定", dag.FAIL: "失敗"}
# A superseded stage is not something to act on -- it is a stage that moved.
# Keeping it out of the attention list is the whole reason the state exists:
# five permanently-amber migration rows were crowding out the two that need a
# decision, and an attention list nobody can act on stops being read.
ACTIONABLE = (dag.WARN, dag.UNKNOWN, dag.FAIL)


def blocks_completion(node):
    """Does this node hold a line back, whatever colour it is showing?

    ACTIONABLE alone was not the right set. A node that is SUPERSEDED and
    still WAITING for its replacement (`llmreview`) counts against completion
    below -- it is in `blocking` -- but it was invisible to the ask matcher,
    which only looked at actionable states. The consequence was quiet and
    wrong: with no ask attached, the owner fell through to the `eng` default,
    so the board said engineering was sitting on something that in fact needed
    a decision nobody had been asked for.

    Retired-and-replaced nodes are NOT blocking (their work moved to a live
    node here), which is the same split the completion block makes, by the
    same heuristic, stated in one place.
    """
    if node["state"] in ACTIONABLE:
        return True
    return node["state"] == dag.SUPERSEDED and "待" in (node.get("detail") or "")

assert set(STATE_ORDER) == set(STATE_LABEL), "state tables disagree"
assert set(STATE_ORDER) == set(dag.RANK), "stage_report and dag disagree on the state set"


# --------------------------------------------------------------------------
# THE MODEL. Everything below renders this and nothing else.
# --------------------------------------------------------------------------

def stage_state(nodes):
    """Worst node wins. A stage with one failing node is not 'mostly fine'."""
    if not nodes:
        return dag.UNKNOWN
    return max((n["state"] for n in nodes), key=lambda s: STATE_ORDER[s])


def matching_asks(nodes):
    """Asks whose bound condition is TRUE RIGHT NOW, for these nodes.

    Both halves are required. A node being amber is not enough -- the detail
    string has to still say what the ask claims it says. `scheduler` going amber
    for an unrelated reason must not resurrect the offsite question next to it.
    """
    out = []
    for a in ASKS:
        for n in nodes:
            if n["id"] != a["node"] or not blocks_completion(n):
                continue
            if a["when"] in n["detail"]:
                out.append(dict(a, node_label=n["label"], node_detail=n["detail"]))
            break
    return out


# How old a supplied board may be before rendering it is a lie. Fifteen minutes
# is the scheduler's own interval for dag.py, so anything older than twice that
# is a board nobody refreshed.
BOARD_MAX_AGE_SECONDS = 1800


def load_board(path):
    """Read a board produced by `dag.py --json`, and refuse a stale one.

    WHY THIS EXISTS. dag.build() probes the live platform: it talks to Docker,
    Postgres, kubectl, Prometheus and the scheduler, and it takes roughly one
    and a half minutes. Two scheduled jobs -- `dag` and `stagereport` -- each
    called it every 15 minutes, so the platform was probed twice per cycle and
    the two artefacts described two DIFFERENT moments. On 2026-09-08 that
    showed up as the board saying FAILED and Stage-Report.json saying DEGRADED
    three minutes apart, from the same underlying state.

    WHY IT REFUSES A STALE FILE. A renderer that will read any JSON on disk is
    a renderer that will happily present last week as today, and a stale status
    page is the specific failure this repo has already paid for twice. So the
    age is checked and the refusal names the age.
    """
    with open(path, encoding="utf-8") as fh:
        board = json.load(fh)
    for key in ("nodes", "verdict"):
        if key not in board:
            raise SystemExit(f"stage_report: {path} has no '{key}' -- that is "
                             f"not a board from dag.py --json")
    stamp = board.get("generated_at")
    if not stamp:
        raise SystemExit(f"stage_report: {path} carries no generated_at, so "
                         f"its age cannot be checked. Refusing: an undatable "
                         f"board is indistinguishable from an old one.")
    try:
        when = datetime.strptime(stamp, "%Y-%m-%dT%H:%M:%SZ").replace(
            tzinfo=timezone.utc)
    except ValueError:
        raise SystemExit(f"stage_report: cannot parse generated_at {stamp!r}")
    age = (datetime.now(timezone.utc) - when).total_seconds()
    if age > BOARD_MAX_AGE_SECONDS:
        raise SystemExit(
            f"stage_report: {path} was generated {int(age)}s ago, over the "
            f"{BOARD_MAX_AGE_SECONDS}s limit. Re-run dag.py --json, or drop "
            f"--from-board and let this probe the platform itself.")
    return board


def stage_model(board=None):
    """Build the single source of truth. Raises rather than renders a page that
    silently omits a node -- a report missing a stage looks exactly like a
    report where that stage is fine."""
    board = dag.build() if board is None else board
    by_id = {n["id"]: n for n in board["nodes"]}

    declared = set()
    for _, _, _, stages in LINES:
        for st in stages:
            declared |= set(st["nodes"])
    missing = sorted(set(by_id) - declared)
    phantom = sorted(declared - set(by_id))
    if missing:
        raise SystemExit(
            "stage_report: dag.py has nodes this report does not show: "
            + ", ".join(missing)
            + "\nAdd them to LINES. A node that is not on any stage is invisible "
              "here, and invisible reads identically to healthy.")
    if phantom:
        raise SystemExit(
            "stage_report: LINES references nodes dag.py does not produce: "
            + ", ".join(phantom))

    lines = []
    all_asks = []
    for line_id, line_name, line_sub, stages in LINES:
        smodels = []
        for st in stages:
            nodes = [by_id[i] for i in st["nodes"]]
            state = stage_state(nodes)
            blocking_nodes = [n for n in nodes if blocks_completion(n)]
            asks = matching_asks(nodes) if blocking_nodes else []
            owner = asks[0]["owner"] if asks else ("eng" if blocking_nodes else None)
            culprits = [n for n in nodes if n["state"] in ACTIONABLE]
            smodels.append({
                "name": st["name"], "why": st["why"], "state": state,
                "owner": owner, "asks": asks,
                "nodes": [{"id": n["id"], "label": n["label"],
                           "state": n["state"], "detail": n["detail"]}
                          for n in nodes],
                "culprits": [{"id": n["id"], "label": n["label"],
                              "state": n["state"], "detail": n["detail"]}
                             for n in culprits],
            })
            for a in asks:
                all_asks.append(dict(a, line=line_name, stage=st["name"], state=state))
        # NODE-LEVEL COMPLETION, WITH ITS DENOMINATOR STATED (2026-09-09).
        #
        # WHY THIS IS SEPARATE FROM THE STAGE COUNTS ABOVE.
        #
        # `green`/`total` above count STAGES. A stage is amber if any node in it
        # is, so DevOps reads 3/9 while its nodes read 16/24. Both are true and
        # they are different questions -- and a reader who does not know which
        # one they are looking at gets 33% or 67% for the same platform.
        #
        # The user's own landing standard is "all three lines at 90%", so the
        # number that standard is measured against has to exist, be generated,
        # and say what it divides by. A hand-written percentage in a document
        # is stale the next time anything moves.
        #
        # SUPERSEDED IS SPLIT, because it hides two different things:
        #   - `retired`: the node was verified and its job moved somewhere that
        #     is itself a live node here (CI/scan/registry/production-like all
        #     moved onto Kubernetes). Counting these as incomplete says work is
        #     missing when it is being done by its replacement.
        #   - `awaiting`: the node was retired and nothing replaced it yet
        #     (`llmreview` still has no Kubernetes artefact wired in).
        # The split is by whether the node's own detail says it is waiting.
        # It is a heuristic, and it is stated here rather than hidden: a reader
        # who disagrees can recount from `nodes` in this same document.
        lnodes = [n for st in smodels for n in st["nodes"]]
        # `or "eng"` at the read site: a stage with no declared owner yields
        # None, and an unowned blocker is engineering work by default --
        # never "nobody's".
        owner_of = {n["id"]: st["owner"] for st in smodels for n in st["nodes"]}
        sup_nodes = [n for n in lnodes if n["state"] == dag.SUPERSEDED]
        awaiting = [n for n in sup_nodes if blocks_completion(n)]
        retired = [n for n in sup_nodes if n not in awaiting]
        n_ok = sum(1 for n in lnodes if n["state"] == dag.OK)
        n_total = len(lnodes)
        lines.append({
            "id": line_id, "name": line_name, "subtitle": line_sub,
            "stages": smodels,
            "green": sum(1 for s in smodels if s["state"] == dag.OK),
            "superseded": sum(1 for s in smodels if s["state"] == dag.SUPERSEDED),
            "total": len(smodels),
            "completion": {
                "denominator": "nodes",
                "nodes_total": n_total,
                "nodes_ok": n_ok,
                "nodes_superseded_retired": len(retired),
                "nodes_superseded_awaiting": len(awaiting),
                "nodes_actionable": n_total - n_ok - len(sup_nodes),
                # STRICT counts only ok. GENEROUS also credits nodes whose job
                # is demonstrably being done by a live replacement. The gap
                # between the two IS the argument, so both are published and
                # neither is called "the" completion.
                "pct_strict": round(100.0 * n_ok / n_total, 1) if n_total else 0.0,
                "pct_crediting_retired": (
                    round(100.0 * (n_ok + len(retired)) / n_total, 1)
                    if n_total else 0.0),
                # THE OWNER TRAVELS WITH THE BLOCKER, and it is declared in
                # LINES rather than judged here.
                #
                # This is what makes a completion target usable instead of
                # motivating. Of the four things holding DevOps below its
                # target, one waits on a decision, two are engineering, and one
                # is retired-awaiting-reconnection; DataOps' single blocker is
                # `external` (a national health agency has not published the
                # calendar mapping) and MLOps' is `research` (the model really
                # does lose to persistence at t+1).
                #
                # ONLY `eng` IS WORK THIS REPOSITORY CAN CLOSE BY ITSELF.
                # Driving `external` or `research` green would mean either
                # waiting on someone else or making a node stop saying a true
                # thing -- and a board that goes green by no longer reporting
                # the bad news is the failure this whole platform is built
                # against. So the split is published next to the percentage.
                "blocking": [
                    {"id": n["id"], "state": n["state"],
                     "owner": (owner_of.get(n["id"]) or "eng"),
                     "detail": (n.get("detail") or "")[:70]}
                    for n in lnodes
                    if n["state"] != dag.OK and n not in retired],
                "blocking_by_owner": {
                    o: sum(1 for n in lnodes
                           if n["state"] != dag.OK and n not in retired
                           and (owner_of.get(n["id"]) or "eng") == o)
                    for o in OWNER_ORDER
                    if any(n["state"] != dag.OK and n not in retired
                           and (owner_of.get(n["id"]) or "eng") == o
                           for n in lnodes)},
            },
        })

    attention = [(l, s) for l in lines for s in l["stages"] if s["state"] in ACTIONABLE]
    by_owner = {o: [] for o in OWNER_ORDER}
    for l, s in attention:
        by_owner[s["owner"]].append({"line": l["name"], **s})

    return {
        "schema": SCHEMA,
        "generated_at": board["generated_at"],
        "verdict": board["verdict"],
        "totals": {
            "green": sum(l["green"] for l in lines),
            "stages": sum(l["total"] for l in lines),
            "superseded": sum(l["superseded"] for l in lines),
            "attention": len(attention),
            "by_owner": {o: len(v) for o, v in by_owner.items()},
        },
        "headline": headline(lines, by_owner),
        "by_owner": by_owner,
        "lines": lines,
        "asks": all_asks,
    }


def headline(lines, by_owner):
    """One sentence, written for someone who will read exactly one sentence.

    It leads with what is being ASKED OF THE READER, not with the tally: a
    reviewer who reads '17/19 綠' and stops has learned nothing about the thing
    that is waiting on them.
    """
    green = sum(l["green"] for l in lines)
    total = sum(l["total"] for l in lines)
    sup = sum(l["superseded"] for l in lines)
    tail = f"{green}/{total} 階段正常" + (f"，{sup} 已遷移至 K8s" if sup else "")
    parts = []
    for o in ("decision", "external", "research"):
        if by_owner[o]:
            parts.append(f"{len(by_owner[o])} 項{OWNER_LABEL[o]}")
    eng = len(by_owner["eng"])
    if not parts and not eng:
        return f"沒有需要決定的事項；{tail}。"
    lead = "、".join(parts) if parts else "沒有需要您決定的事項"
    if eng:
        lead += f"；另有 {eng} 項工程自理"
    return f"{lead}。{tail}。"


# --------------------------------------------------------------------------
# RENDERER: markdown digest, for an AI or a chat message.
#
# Sized on purpose. Non-green stages get their culprits and their ask; green
# stages collapse to one table row. The reader that needs every node's detail
# has the JSON; what this one needs is to fit in a prompt and still contain
# every fact required to answer "what is wrong and whose move is it".
# --------------------------------------------------------------------------

def render_markdown(m):
    t = m["totals"]
    # OKF v0.1 frontmatter, emitted rather than hand-written. The repo's other
    # markdown carries it so an agent can consume the tree as a knowledge
    # bundle (platform/docs/okf_check.py enforces it); a generated file that
    # opted out would be the one document in the bundle an agent has to open
    # and parse specially. `review` is the spec-local type for a
    # point-in-time assessment, which is exactly what this is.
    out = [
        "---",
        "type: review",
        "title: 三線階段燈號",
        'description: "Live stage-level status for DevOps, DataOps and MLOps, '
        'grouped by whose move it is. Generated from probes, never hand-edited."',
        "tags:",
        "  - status",
        "  - devops",
        "  - dataops",
        "  - mlops",
        f"timestamp: {m['generated_at']}",
        "generator: platform/statusdag/stage_report.py",
        "---",
        "",
        "# 三線階段燈號",
        "",
        "<!-- 這份檔案是產生的，不要手動編輯：下一次排程執行會整份覆蓋。 -->",
        "",
        f"- schema: `{m['schema']}`",
        f"- generated: `{m['generated_at']}`",
        f"- verdict: `{m['verdict']}`",
        f"- 階段: {t['green']}/{t['stages']} 正常"
        + (f"，{t['superseded']} 已被取代（遷移至 K8s）" if t["superseded"] else ""),
        "",
        f"> {m['headline']}",
        "",
        "每一盞燈都是本次執行的實測（查資料庫、問叢集、讀證據檔），不是文件記載。",
        "階段只有在底下每個節點都正常時才是綠的。",
        "",
        "## 三條線的完成度（分母是節點，不是階段）",
        "",
        "同一個平台會給出兩個百分比，因為分母不同：**階段**的綠燈率與**節點**的",
        "綠燈率。上面那一行是階段；下面這張表是節點，而落地標準應該對著節點看",
        "——階段只要有一個節點不綠就整段不綠，它答的是「哪一段要注意」，",
        "不是「做完多少」。",
        "",
        "**`阻擋者` 那一欄比百分比重要。** 只有 `eng` 是這個 repo 自己關得掉的：",
        "`external` 在等別人（例如疾管署發布對照）、`research` 是模型真的還沒贏過",
        "基準、`decision` 在等使用者拍板。**把 `external` 或 `research` 逼成綠色，",
        "只有兩條路：等別人，或讓某個節點不再說一句真話**——而後者正是這整個平台",
        "存在要防的事。",
        "",
        "| 線 | 節點綠燈 | 計入「已被取代且有替代品」 | 阻擋者（依歸屬） |",
        "|---|---:|---:|---|",
    ] + [
        (f"| {l['name']} | {l['completion']['pct_strict']}% "
         f"({l['completion']['nodes_ok']}/{l['completion']['nodes_total']}) "
         f"| {l['completion']['pct_crediting_retired']}% | "
         + ("、".join(f"{OWNER_LABEL.get(o, o)} {n}"
                      for o, n in l["completion"]["blocking_by_owner"].items())
            or "無")
         + " |")
        for l in m["lines"]
    ] + [
        "",
    ]

    for owner in OWNER_ORDER:
        items = m["by_owner"][owner]
        out.append(f"## {OWNER_LABEL[owner]}（{len(items)}）")
        out.append("")
        if not items:
            out += ["（無）", ""]
            continue
        for s in items:
            out.append(f"### {s['line']} · {s['name']} — {STATE_LABEL[s['state']]}")
            for c in s["culprits"]:
                out.append(f"- `{c['id']}` {c['label']}：{c['detail']}")
            for a in s["asks"]:
                out.append(f"- **問題**：{a['ask']}")
                for opt in a["options"]:
                    out.append(f"  - 可選：{opt}")
                out.append(f"  - 參考：`{a['ref']}`（ask id `{a['id']}`）")
            out.append("")

    out += ["## 全部階段", "", "| 線 | 階段 | 狀態 | 這一段負責什麼 |",
            "|---|---|---|---|"]
    for l in m["lines"]:
        for s in l["stages"]:
            out.append(f"| {l['name']} | {s['name']} | {STATE_LABEL[s['state']]} | {s['why']} |")
    out += ["",
            "產生自 `platform/statusdag/stage_report.py`；探測邏輯 `platform/statusdag/dag.py`。",
            "完整節點資料見 `docs/Stage-Report.json`，圖與看板見 `docs/Stage-Report.html`。",
            ""]
    return "\n".join(out)


def render_json(m):
    return json.dumps(m, ensure_ascii=False, indent=2) + "\n"


# --------------------------------------------------------------------------
# SELFCHECK. The hand-written metadata in this file is the only part that can
# be wrong without anything failing, so it is the only part with a test.
# --------------------------------------------------------------------------

def selfcheck(board=None):
    # board is threaded through for the same reason stage_model takes it: the
    # metadata this validates (stages, asks, node coverage) does not depend on
    # what the platform is doing, and probing the live platform to check a
    # hand-written list is both slow and non-deterministic.
    m = stage_model(board)       # raises on any node/stage coverage gap
    problems, notes = [], []

    node_ids = {n["id"] for l in m["lines"] for s in l["stages"] for n in s["nodes"]}
    seen = set()
    for a in ASKS:
        if a["id"] in seen:
            problems.append(f"ask id 重複：{a['id']}")
        seen.add(a["id"])
        if a["node"] not in node_ids:
            problems.append(f"ask {a['id']} 綁在不存在的節點 {a['node']}")
        if a["owner"] not in OWNER_LABEL:
            problems.append(f"ask {a['id']} 的 owner 不合法：{a['owner']}")
        if a["owner"] == "eng":
            problems.append(f"ask {a['id']} 的 owner 是 eng——eng 是沒有 ask 時的預設，"
                            "寫成 ask 表示它其實在等某個人")
        if not a["options"]:
            problems.append(f"ask {a['id']} 沒有可選項——只描述問題不給選項，讀的人無法決定")
        ref = os.path.join(REPO_ROOT, a["ref"])
        if not os.path.exists(ref):
            problems.append(f"ask {a['id']} 指向不存在的檔案 {a['ref']}")

    live = {a["id"] for a in m["asks"]}
    for a in ASKS:
        if a["id"] not in live:
            notes.append(f"ask {a['id']} 目前沒有對應到任何現況"
                         f"（節點 {a['node']} 已正常，或 detail 不再包含 \"{a['when']}\"）"
                         "——條件已消失，這筆該刪或該改")

    for l in m["lines"]:
        for s in l["stages"]:
            if not s["why"].strip():
                problems.append(f"{l['name']} · {s['name']} 沒有說明")

    for p in problems:
        print(f"FAIL  {p}")
    for n in notes:
        print(f"NOTE  {n}")
    if not problems and not notes:
        print("OK    節點覆蓋完整，ASKS 全部對應到現況")
    elif not problems:
        print(f"OK    無錯誤；{len(notes)} 筆 ask 待清理")
    return 1 if problems else 0


# --------------------------------------------------------------------------
# RENDERER: the page. For a human in the room, and for the reviewer who will
# read the first screen and the diagrams and nothing else.
# --------------------------------------------------------------------------

def esc(text):
    return html.escape(str(text), quote=True)


# THE EIGHT DIAGRAMS LIVE IN EXACTLY ONE PLACE (2026-09-02).
#
# Until today they lived in two, and the two had drifted apart completely.
#
# `docs/diagrams/*.html` held eight hand-authored inline SVGs from 2026-08-25,
# and this file embedded them. `docs/report/plates.src.html` holds eight
# mermaid plates built for the stage report to management. Same eight subjects,
# independently written, near-zero shared label text when compared -- and the
# older set still said "31 tests" and did not contain Kubernetes at all.
#
# So the board showed one architecture and the deck showed another, to the same
# reader, both labelled current. That is the two-index divergence problem in
# the two artefacts most likely to be put in front of somebody senior.
#
# The stale set is deleted. This page now LINKS to the single source instead of
# carrying a copy, which costs the inline figures and buys the guarantee that
# there is nothing left to diverge from. Restoring inline figures means
# rendering the mermaid source to SVG at build time -- a real option, recorded
# in docs/Backlog.md, and not one to fake by hand-drawing a second set again.

PLATES_HREF = "report/plates.offline.html"

# Which plate answers which line. Anchors are the section ids in plates.src.html.
PLATE_ANCHOR = {
    "devops":   ("p1", "p2"),
    "dataops":  ("p3", "p4"),
    "mlops":    ("p5", "p6"),
    "unified":  ("p8", "p7"),
}


def plate_links(line_id, line_name):
    """A link to the one source, not a second copy of it."""
    pair = PLATE_ANCHOR.get(line_id)
    if not pair:
        return ""
    arch, flow = pair
    return (
        '<p class="plates">圖：'
        f'<a href="{PLATES_HREF}#{arch}">{esc(line_name)} 架構圖</a>　'
        f'<a href="{PLATES_HREF}#{flow}">{esc(line_name)} 流程圖</a>'
        '<small>八張圖只有一份來源，離線可開</small></p>')


def render_html(m):
    t = m["totals"]

    # -- attention, grouped by whose move it is ----------------------------
    groups = ""
    for owner in OWNER_ORDER:
        items = m["by_owner"][owner]
        if not items:
            continue
        rows = ""
        for s in items:
            culprits = "、".join(f"{esc(c['label'])}（{esc(c['detail'])}）"
                                 for c in s["culprits"])
            asks = ""
            for a in s["asks"]:
                opts = "".join(f"<li>{esc(o)}</li>" for o in a["options"])
                asks += (f'<p class="ask">{esc(a["ask"])}</p>'
                         f'<ul class="opts">{opts}</ul>'
                         f'<p class="ref">參考 <code>{esc(a["ref"])}</code>'
                         f' · ask id <code>{esc(a["id"])}</code></p>')
            rows += (f'<li class="s-{esc(s["state"])}">'
                     f'<b>{esc(s["line"])} · {esc(s["name"])}</b>'
                     f'<span class="culprit">{culprits}</span>'
                     f'{asks}</li>')
        groups += (f'<div class="grp o-{esc(owner)}">'
                   f'<h4>{esc(OWNER_LABEL[owner])}'
                   f'<span class="cnt">{len(items)}</span></h4>'
                   f'<ul class="attention">{rows}</ul></div>')
    if not groups:
        groups = '<p class="all-clear">所有階段正常，沒有待決事項。</p>'

    # -- lines --------------------------------------------------------------
    line_html = ""
    for l in m["lines"]:
        cards = ""
        for s in l["stages"]:
            nodes = "".join(
                f'<li class="n s-{esc(n["state"])}">'
                f'<span class="nl">{esc(n["label"])}</span>'
                f'<span class="nd">{esc(n["detail"])}</span></li>'
                for n in s["nodes"])
            badge = ""
            if s["owner"] and s["owner"] != "eng":
                badge = f'<span class="owner o-{esc(s["owner"])}">{esc(OWNER_LABEL[s["owner"]])}</span>'
            cards += (f'<article class="stage s-{esc(s["state"])}">'
                      f'<header><h4>{esc(s["name"])}</h4>'
                      f'<span class="pill">{esc(STATE_LABEL[s["state"]])}</span></header>'
                      f'{badge}'
                      f'<p class="why">{esc(s["why"])}</p>'
                      f'<ul class="nodes">{nodes}</ul></article>')
        # Named on the line header too, not only in the global tally: a reader
        # who sees "4 / 9" without it will assume five things are broken.
        sup = f"，{l['superseded']} 已被取代" if l["superseded"] else ""
        figs = plate_links(l["id"], l["name"])
        line_html += (
            f'<section class="line" data-line="{esc(l["id"])}">'
            f'<header class="line-head">'
            f'<div><p class="eyebrow">{esc(l["subtitle"])}</p>'
            f'<h2>{esc(l["name"])}</h2></div>'
            f'<span class="score">{l["green"]} / {l["total"]}'
            f'<small>階段正常{sup}</small></span></header>'
            f'<div class="figs">{figs}</div>'
            f'<div class="stages">{cards}</div></section>')

    unified = plate_links("unified", "三線統整")

    tally = "".join(
        f'<div class="{l["id"]}"><span class="n">{l["green"]} / {l["total"]}</span>'
        f'<span class="k">{esc(l["name"])}</span></div>' for l in m["lines"])

    return (HEAD + CSS + f"""
<div class="wrap">
  <header class="top">
    <p class="eyebrow">階段檢視 · 由現場探測產生</p>
    <h1>三線階段燈號</h1>
    <p class="stamp">產生於 {esc(m['generated_at'])}</p>
    <p class="headline">{esc(m['headline'])}</p>
    <p class="lede">
      每一盞燈都來自<strong>當下的實測</strong>——查資料庫、問叢集、讀證據檔，不是文件上的記載。
      一個階段只有在它底下每個節點都正常時才是綠的；不是綠的，下面會寫出是哪個節點造成的，
      以及<strong>下一步在誰手上</strong>。
    </p>
    <div class="tally">
      <div><span class="n">{t['green']} / {t['stages']}</span><span class="k">階段正常（全平台）</span></div>
      <div><span class="n">{t['superseded']}</span><span class="k">已被取代（遷移到 K8s）</span></div>
      {tally}
    </div>
  </header>

  <section>
    <h3>需要注意的階段</h3>
    <p class="note">依<strong>下一步在誰手上</strong>分組。「待您決定」的項目工程端無法自行推進；
      「工程自理」不需要您做任何事，列出只是為了不隱瞞。</p>
    <div class="groups">{groups}</div>
  </section>

  <section>
    <h3>三線統整</h3>
    {unified}
  </section>

  {line_html}

  <footer>
    <span>本頁由 <code>platform/statusdag/stage_report.py</code> 產生，由排程器每 15 分鐘重跑；
      標題下的時間戳記是它唯一的有效期宣告。</span>
    <span>同一份資料另有兩種格式：<code>docs/Stage-Report.json</code>（完整節點資料，供程式判讀）、
      <code>docs/Stage-Report.md</code>（精簡摘要，供 AI 讀取）。</span>
    <span>八張圖的<strong>唯一</strong>來源是 <code>docs/report/plates.src.html</code>
      （離線版 <a href="report/plates.offline.html">report/plates.offline.html</a>）；
      節點探測邏輯 <code>platform/statusdag/dag.py</code>。
      2026-09-02 之前本頁內嵌 <code>docs/diagrams/</code> 的第二套圖，兩套已完全分岔，舊的那套已刪。</span>
    <span><a href="/decisions/index.md">決策紀錄</a>——每一筆帶量測的決定都附重跑指令，
      所以三個月後是重跑一次，不是憑印象重估。</span>
  </footer>
</div>
""")


HEAD = """<title>三線階段燈號</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=Noto+Sans+TC:wght@400;500;700&family=Noto+Serif+TC:wght@600;700&display=swap">
"""

CSS = """<style>
:root {
  --ground:#F5F6F8; --surface:#FFFFFF; --sunk:#ECEFF3;
  --ink:#171C24; --soft:#4E5966; --faint:#7A8593;
  --rule:#D6DCE3; --rule-soft:#E6EAEF;
  --devops:#2E5AA8; --dataops:#2F7D52; --mlops:#8A5A2B;
  --ok:#2F7D52; --warn:#A8792A; --fail:#A8372C; --unknown:#6E7A88;
  --ok-w:#E6F0EA; --warn-w:#F7EFDD; --fail-w:#F7E7E5; --unknown-w:#EDF0F3;
  --decision:#8A4B9E; --decision-w:#F1E8F5;
  --external:#1F6F7A; --external-w:#E1EFF1;
  --research:#8A5A2B; --research-w:#F5ECE1;
}
@media (prefers-color-scheme:dark) {
  :root:not([data-theme="light"]) {
    --ground:#12161C; --surface:#1A2029; --sunk:#212932;
    --ink:#E3E8EE; --soft:#A7B2BF; --faint:#79848F;
    --rule:#303A45; --rule-soft:#252E38;
    --devops:#7FA8E0; --dataops:#6FBF93; --mlops:#C99C6E;
    --ok:#6FBF93; --warn:#D9AE5C; --fail:#E28078; --unknown:#79848F;
    --ok-w:#182C21; --warn-w:#2E2612; --fail-w:#321F1D; --unknown-w:#212932;
    --decision:#C79AD8; --decision-w:#2A1E31;
    --external:#68B8C4; --external-w:#122A2E;
    --research:#C99C6E; --research-w:#2C2216;
  }
}
:root[data-theme="dark"] {
  --ground:#12161C; --surface:#1A2029; --sunk:#212932;
  --ink:#E3E8EE; --soft:#A7B2BF; --faint:#79848F;
  --rule:#303A45; --rule-soft:#252E38;
  --devops:#7FA8E0; --dataops:#6FBF93; --mlops:#C99C6E;
  --ok:#6FBF93; --warn:#D9AE5C; --fail:#E28078; --unknown:#79848F;
  --ok-w:#182C21; --warn-w:#2E2612; --fail-w:#321F1D; --unknown-w:#212932;
  --decision:#C79AD8; --decision-w:#2A1E31;
  --external:#68B8C4; --external-w:#122A2E;
  --research:#C99C6E; --research-w:#2C2216;
}
*{box-sizing:border-box}
body{margin:0;background:var(--ground);color:var(--ink);line-height:1.8;
  font-family:"Noto Sans TC","PingFang TC",system-ui,sans-serif;font-size:15px;
  -webkit-font-smoothing:antialiased;padding:0 1.5rem 5rem}
.wrap{max-width:78rem;margin:0 auto;display:flex;flex-direction:column;gap:3.5rem}
h1,h2,h3,h4{font-family:"Noto Serif TC","Songti TC",serif;margin:0;text-wrap:balance;line-height:1.35}
.eyebrow{font-family:"IBM Plex Mono",ui-monospace,monospace;font-size:.7rem;
  letter-spacing:.14em;text-transform:uppercase;color:var(--faint);margin:0}

header.top{padding-top:3.5rem;display:flex;flex-direction:column;gap:1rem}
header.top h1{font-size:clamp(2rem,4.5vw,2.9rem)}
.stamp{font-family:"IBM Plex Mono",ui-monospace,monospace;font-size:.8rem;color:var(--faint);margin:0}
.headline{margin:.5rem 0 0;font-size:clamp(1.05rem,2vw,1.3rem);font-weight:500;
  line-height:1.7;max-width:62ch;border-left:4px solid var(--accent,var(--devops));
  padding-left:1rem}
.lede{max-width:64ch;color:var(--soft);margin:0}
.note{margin:0;color:var(--soft);font-size:.9rem;max-width:66ch}
.tally{display:flex;flex-wrap:wrap;gap:2.25rem;border-top:1px solid var(--rule);
  padding-top:1.25rem;margin-top:.25rem}
.tally div{display:flex;flex-direction:column}
.tally .n{font-family:"IBM Plex Mono",ui-monospace,monospace;font-variant-numeric:tabular-nums;
  font-size:1.9rem;line-height:1.15;font-weight:500}
.tally .k{font-size:.78rem;color:var(--faint)}
.tally .devops .n{color:var(--devops)}
.tally .dataops .n{color:var(--dataops)}
.tally .mlops .n{color:var(--mlops)}

section{display:flex;flex-direction:column;gap:1.5rem}
section > h3{font-size:1.35rem;border-bottom:2px solid var(--rule);padding-bottom:.5rem}

figure{margin:0;display:flex;flex-direction:column;gap:.5rem}
figcaption{font-family:"IBM Plex Mono",ui-monospace,monospace;font-size:.72rem;
  letter-spacing:.1em;text-transform:uppercase;color:var(--faint)}
/* The diagrams are light-mode artwork with their own white ground. Painting a
   dark frame around them made a white plate look like a rendering failure, so
   the frame matches the plate in both themes -- a deliberate printed page
   rather than an accident. */
.canvas{background:#FBFCFD;border:1px solid var(--rule-soft);border-radius:3px;
  padding:.5rem;overflow-x:auto}
.canvas svg{display:block;min-width:900px;width:100%;height:auto}
.missing{color:var(--fail);font-size:.9rem;margin:0}
.figs{display:flex;flex-direction:column;gap:1.5rem}
.plates{margin:0;padding:.7rem .9rem;border:1px solid var(--rule-soft);border-radius:3px;
  background:#FBFCFD;font-size:.82rem}
.plates a{font-weight:600;text-decoration:none;border-bottom:1px solid currentColor}
.plates small{display:block;margin-top:.3rem;color:var(--muted);font-size:.72rem}

.groups{display:flex;flex-direction:column;gap:1.5rem}
.grp{background:var(--surface);border:1px solid var(--rule-soft);border-radius:3px;
  border-top:3px solid var(--tone);padding:1.1rem 1.3rem;--tone:var(--faint);--tone-w:var(--sunk)}
.grp.o-decision{--tone:var(--decision);--tone-w:var(--decision-w)}
.grp.o-external{--tone:var(--external);--tone-w:var(--external-w)}
.grp.o-research{--tone:var(--research);--tone-w:var(--research-w)}
.grp h4{font-size:1.1rem;color:var(--tone);display:flex;align-items:center;gap:.6rem}
.grp .cnt{font-family:"IBM Plex Mono",ui-monospace,monospace;font-size:.75rem;
  background:var(--tone-w);color:var(--tone);border-radius:999px;padding:.05rem .6rem;line-height:1.8}
.attention{list-style:none;margin:.6rem 0 0;padding:0;display:flex;flex-direction:column;gap:0}
.attention li{display:flex;flex-direction:column;gap:.2rem;padding:.9rem 0;
  border-top:1px solid var(--rule-soft)}
.attention li:first-child{border-top:none;padding-top:.2rem}
.attention b{font-size:.98rem}
.culprit{color:var(--soft);font-size:.87rem}
.ask{margin:.4rem 0 0;font-size:.92rem;color:var(--ink)}
.opts{margin:.35rem 0 0;padding-left:1.2rem;color:var(--soft);font-size:.87rem;
  line-height:1.6}
.opts li{margin:.2rem 0}
.ref{margin:.45rem 0 0;font-size:.75rem;color:var(--faint)}
.all-clear{color:var(--ok);margin:0}

.line{border-top:3px solid var(--accent);padding-top:1.5rem}
.line[data-line="devops"]{--accent:var(--devops)}
.line[data-line="dataops"]{--accent:var(--dataops)}
.line[data-line="mlops"]{--accent:var(--mlops)}
.line-head{display:flex;align-items:flex-end;justify-content:space-between;
  gap:1rem;flex-wrap:wrap}
.line-head h2{font-size:1.7rem;color:var(--accent)}
.score{font-family:"IBM Plex Mono",ui-monospace,monospace;font-variant-numeric:tabular-nums;
  font-size:1.5rem;font-weight:500;color:var(--accent);display:flex;align-items:baseline;gap:.5rem}
.score small{font-family:"Noto Sans TC",sans-serif;font-size:.75rem;color:var(--faint)}

.stages{display:grid;grid-template-columns:repeat(auto-fill,minmax(19rem,1fr));gap:1rem}
.stage{background:var(--surface);border:1px solid var(--rule-soft);
  border-left:4px solid var(--tone);border-radius:3px;padding:1rem 1.15rem;
  display:flex;flex-direction:column;gap:.6rem;--tone:var(--ok);--tone-w:var(--ok-w)}
.stage.s-warn{--tone:var(--warn);--tone-w:var(--warn-w)}
.stage.s-fail{--tone:var(--fail);--tone-w:var(--fail-w)}
.stage.s-unknown{--tone:var(--unknown);--tone-w:var(--unknown-w)}
.stage.s-superseded{--tone:var(--faint);--tone-w:var(--sunk);opacity:.72}
.stage header{display:flex;align-items:baseline;justify-content:space-between;gap:.75rem}
.stage h4{font-size:1.02rem}
.pill{font-size:.7rem;letter-spacing:.06em;color:var(--tone);background:var(--tone-w);
  border-radius:999px;padding:.05rem .6rem;white-space:nowrap;line-height:1.7}
.owner{align-self:flex-start;font-size:.7rem;letter-spacing:.06em;border-radius:2px;
  padding:.05rem .55rem;line-height:1.8;background:var(--sunk);color:var(--faint)}
.owner.o-decision{background:var(--decision-w);color:var(--decision)}
.owner.o-external{background:var(--external-w);color:var(--external)}
.owner.o-research{background:var(--research-w);color:var(--research)}
.why{margin:0;font-size:.85rem;color:var(--soft);line-height:1.65}
.nodes{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:.3rem;
  border-top:1px dashed var(--rule);padding-top:.6rem}
/* Scoped to .nodes on purpose: `.n` is also the tally's number span, and an
   unscoped `.n::before` painted a status dot in front of every headline
   figure. Same class, two meanings, one stylesheet -- so the selector has to
   say which one it means. */
.nodes .n{display:flex;gap:.5rem;align-items:baseline;font-size:.82rem;flex-wrap:wrap}
.nodes .n::before{content:"";width:.5rem;height:.5rem;border-radius:999px;flex:none;
  background:var(--ok);transform:translateY(-1px)}
.nodes .n.s-warn::before{background:var(--warn)}
.nodes .n.s-fail::before{background:var(--fail)}
.nodes .n.s-unknown::before{background:var(--unknown)}
.nodes .n.s-superseded::before{background:var(--faint);opacity:.6}
.nl{font-weight:500;white-space:nowrap}
.nd{color:var(--faint);font-family:"IBM Plex Mono",ui-monospace,monospace;font-size:.72rem;
  font-variant-numeric:tabular-nums}

footer{border-top:1px solid var(--rule);padding-top:1.25rem;color:var(--faint);
  font-size:.82rem;display:flex;flex-direction:column;gap:.35rem}
code{font-family:"IBM Plex Mono",ui-monospace,monospace;font-size:.85em;
  background:var(--sunk);padding:.1em .4em;border-radius:3px}
</style>
"""

RENDERERS = {
    "html": (render_html, "Stage-Report.html"),
    "json": (render_json, "Stage-Report.json"),
    "md":   (render_markdown, "Stage-Report.md"),
}


def main():
    ap = argparse.ArgumentParser(description="Stage-level status, three renderings")
    ap.add_argument("--format", choices=["html", "json", "md", "all"], default="all")
    ap.add_argument("--out-dir", default=DOCS)
    ap.add_argument("--stdout", action="store_true",
                    help="write to stdout instead of a file (single format only)")
    ap.add_argument("--selfcheck", action="store_true",
                    help="validate the hand-written stage/ask metadata and exit")
    ap.add_argument("--from-board", metavar="PATH",
                    help="render from a board already produced by "
                         "`dag.py --json` instead of probing the platform "
                         "again. Refuses a board older than "
                         f"{BOARD_MAX_AGE_SECONDS}s.")
    args = ap.parse_args()

    if args.selfcheck:
        return selfcheck(load_board(args.from_board) if args.from_board else None)

    fmts = list(RENDERERS) if args.format == "all" else [args.format]
    if args.stdout and len(fmts) != 1:
        ap.error("--stdout needs a single --format")

    model = stage_model(load_board(args.from_board) if args.from_board else None)
    if args.stdout:
        sys.stdout.write(RENDERERS[fmts[0]][0](model))
        return 0

    os.makedirs(args.out_dir, exist_ok=True)
    for f in fmts:
        fn, name = RENDERERS[f]
        path = os.path.join(args.out_dir, name)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(fn(model))
        print(f"artifact={path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
