#!/usr/bin/env bash
# Sources Grafana's admin credential from Vault and delivers it to Compose.
#
# This exists to demonstrate the full chain the platform claims to have:
#
#   Vault (source of truth) -> bootstrap script -> gitignored env file
#     -> container environment -> Grafana
#
# The env file is a delivery detail, not a second source of truth. Rotating
# the credential means rotating it in Vault and re-running this script; the
# file is disposable and regenerable, which is exactly what distinguishes it
# from the `.env`-as-secret-store pattern this platform moved away from.
#
# Idempotent: if secret/devops/grafana-admin does not exist yet, one is
# generated and written to Vault first. The password is never printed.
#
# Usage:
#   platform/observability/scripts/bootstrap_grafana_admin.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OBS_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$OBS_DIR/../.." && pwd)"
VAULT_DIR="$REPO_ROOT/platform/vault"
ENV_FILE="$OBS_DIR/.grafana.env"
CONTAINER="${VAULT_CONTAINER:-vault-vault-1}"
SECRET_PATH="secret/devops/grafana-admin"

if ! docker ps --format '{{.Names}}' | grep -qx "$CONTAINER"; then
  echo "Vault container '$CONTAINER' is not running." >&2
  exit 1
fi

if [ -z "${VAULT_TOKEN:-}" ]; then
  VAULT_TOKEN="$(python3 -c "
import json
print(json.load(open('$VAULT_DIR/.init-output.json'))['root_token'])
")"
fi

v() {
  docker exec -i -e VAULT_TOKEN="$VAULT_TOKEN" -e VAULT_ADDR=http://127.0.0.1:8200 \
    "$CONTAINER" vault "$@" </dev/null
}

if v kv get -field=password "$SECRET_PATH" >/dev/null 2>&1; then
  echo "Using existing $SECRET_PATH"
else
  echo "No credential at $SECRET_PATH -- generating one."
  PASSWORD="$(python3 -c "import secrets; print(secrets.token_urlsafe(24))")"
  # Passed via stdin so the value never appears in a command line (`ps`).
  printf '%s' "$PASSWORD" | docker exec -i \
    -e VAULT_TOKEN="$VAULT_TOKEN" -e VAULT_ADDR=http://127.0.0.1:8200 \
    "$CONTAINER" vault kv put "$SECRET_PATH" username=admin password=- >/dev/null
  # `password=-` reads the value from stdin; confirm it landed rather than
  # assuming, since a silent miswrite here locks everyone out of Grafana.
  v kv get -field=password "$SECRET_PATH" >/dev/null
  echo "Generated and stored (value not printed)."
fi

umask 077
{
  echo "# Generated by platform/observability/scripts/bootstrap_grafana_admin.sh"
  echo "# Source of truth is Vault at $SECRET_PATH. This file is disposable:"
  echo "# delete it and re-run the script to regenerate."
  echo "GF_SECURITY_ADMIN_USER=$(v kv get -field=username "$SECRET_PATH")"
  echo "GF_SECURITY_ADMIN_PASSWORD=$(v kv get -field=password "$SECRET_PATH")"
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"

echo "Wrote $ENV_FILE (chmod 600, gitignored). No secret value printed."

# ---------------------------------------------------------------------
# Reset the LIVE admin password.
#
# This step is not redundant with GF_SECURITY_ADMIN_PASSWORD, and assuming
# it was is a real trap: that variable is only honoured when Grafana
# initialises its database for the FIRST time. On any existing grafana-data
# volume it is silently ignored, and the admin account keeps whatever
# password it already had -- here, the default admin/admin.
#
# The failure mode is worse than doing nothing: turning anonymous access off
# while leaving admin/admin live converts "everyone is a viewer" into
# "anyone who tries the most-guessed credential on earth is an admin", while
# the config reads as though access was locked down. Verified by observing
# exactly that: `curl -u admin:admin` succeeded after the env var was set.
# ---------------------------------------------------------------------
GRAFANA_CONTAINER="${GRAFANA_CONTAINER:-observability-grafana-1}"
if docker ps --format '{{.Names}}' | grep -qx "$GRAFANA_CONTAINER"; then
  ADMIN_USER="$(v kv get -field=username "$SECRET_PATH")"
  # --password-from-stdin is the CLI's own supported way to avoid putting the
  # password in argv (where `ps` would show it). --homepath is a GLOBAL flag
  # and must precede the `admin` subcommand; placing it after fails with
  # "flag provided but not defined: -homepath".
  v kv get -field=password "$SECRET_PATH" \
    | docker exec -i "$GRAFANA_CONTAINER" \
        grafana cli --homepath /usr/share/grafana \
        admin reset-admin-password --password-from-stdin >/dev/null 2>&1

  # Read the BODY, not just the status code. Grafana blocks a user after a few
  # consecutive failed logins and a blocked account also answers 401 -- so
  # "did not take effect" was being reported for an account that was merely
  # rate-limited, and the operator was sent to check a password that was
  # already correct. Observed on 2026-08-25 during the first real rotation:
  # "too many consecutive incorrect login attempts for user".
  RESET_BODY="$(curl -s -w '\n%{http_code}' \
    -u "$ADMIN_USER:$(v kv get -field=password "$SECRET_PATH")" \
    http://127.0.0.1:13000/api/org)"
  case "$RESET_BODY" in
    *$'\n'200) echo "Live admin password reset to the Vault-held credential (verified)." ;;
    *"temporarily blocked"*)
      echo "UNVERIFIED: Grafana has rate-limited this account, so the new" >&2
      echo "            password could not be confirmed. It is NOT known to be" >&2
      echo "            wrong -- retry in a few minutes." >&2 ;;
    *) echo "WARNING: admin password reset did not take effect -- check manually." >&2 ;;
  esac

  # Confirm the default is genuinely dead, rather than trusting the reset.
  if curl -s -o /dev/null -w '%{http_code}' -u admin:admin \
       http://127.0.0.1:13000/api/org | grep -q 200; then
    echo "WARNING: admin/admin STILL WORKS. Do not consider Grafana locked down." >&2
  else
    echo "Default admin/admin no longer accepted (verified)."
  fi
else
  echo "NOTE: $GRAFANA_CONTAINER not running -- skipped live password reset."
  echo "      Re-run this script after 'docker compose up -d grafana'."
fi

echo "Apply config changes: cd platform/observability && docker compose up -d grafana"
