#!/usr/bin/env bash
# Render the pilot's AppRole into the env file compose reads.
#
# WHY THIS EXISTS (2026-09-01).
#
# `pilots/station2-twin/compose.yaml` takes its Vault AppRole from the ambient
# environment:
#
#     VAULT_ROLE_ID: ${VAULT_ROLE_ID:-}
#     VAULT_SECRET_ID: ${VAULT_SECRET_ID:-}
#
# and the app falls back to the static password when they are empty. That
# fallback is deliberate and documented -- the pilot must still run without
# Vault. What was NOT deliberate is how easily it happens by accident: any
# restart from a shell that does not happen to have those variables exported
# silently downgrades the credential model, and nothing says so.
#
# It happened. The whole container set stopped (laptop sleep), `recover.sh`
# brought it back with `docker compose up`, and the develop copy came back on
# `mode: static` while the Kubernetes copy -- which gets its AppRole from a
# Secret the deploy script syncs -- came back on `mode: vault`. The two copies
# had swapped places compared with the morning, and the only reason anyone knew
# is that `test_migration_observed.sh` had started comparing them hours earlier.
#
# `.gitignore` has carried an entry for `pilots/station2-twin/.env.vault` --
# "AppRole secret_id delivered to the pilot container. Regenerable from Vault;
# never committed" -- for weeks. NOTHING WROTE IT AND NOTHING READ IT. The
# convention was declared and never wired up: another thing that registers as
# present and does not execute.
#
# This is the same fix already applied on the Kubernetes side: make the start
# path OWN its prerequisite instead of hoping the operator's shell has it.
#
# Usage:
#   write_pilot_approle_env.sh [pilot]        # default station2-twin
#
# Exit codes:
#   0  env file written
#   1  no AppRole file -- says so loudly and writes nothing
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
PILOT="${1:-station2-twin}"

APPROLE="$REPO_ROOT/platform/vault/.${PILOT}-approle.json"
ENV_FILE="$REPO_ROOT/pilots/$PILOT/.env.vault"

if [ ! -f "$APPROLE" ]; then
  # Loud, and non-zero. The caller decides whether to continue -- but it must
  # be a decision, not a default. Running on the static password is a supported
  # mode; arriving there without noticing is the failure.
  echo "  WARNING: $APPROLE not found." >&2
  echo "  $PILOT will start on the STATIC database password, not Vault." >&2
  echo "  Create the AppRole with:" >&2
  echo "    platform/vault/scripts/setup_database_secrets.sh $PILOT 15432" >&2
  exit 1
fi

# Written via python rather than shell interpolation so the secret never
# becomes an argv element -- `ps` is world-readable on this machine. umask is
# set before creation, not chmod'ed after: a chmod leaves a window in which the
# file exists and is world-readable.
python3 - "$APPROLE" "$ENV_FILE" <<'PY'
import json
import os
import sys

approle_path, env_path = sys.argv[1:3]
with open(approle_path) as handle:
    data = json.load(handle)

role_id = data.get("role_id", "")
secret_id = data.get("secret_id", "")
if not role_id or not secret_id:
    sys.stderr.write("  WARNING: %s has no role_id/secret_id\n" % approle_path)
    raise SystemExit(1)

old_umask = os.umask(0o077)
try:
    with open(env_path, "w") as handle:
        handle.write(
            "# Generated by platform/vault/scripts/write_pilot_approle_env.sh.\n"
            "# Gitignored. Regenerable from Vault; never commit this file.\n"
            "VAULT_ROLE_ID=%s\nVAULT_SECRET_ID=%s\n" % (role_id, secret_id)
        )
finally:
    os.umask(old_umask)
PY
rc=$?
[ "$rc" -eq 0 ] || exit 1

ROLE_PREFIX="$(python3 -c "
import json,sys
print(json.load(open(sys.argv[1]))['role_id'][:8])" "$APPROLE")"
echo "  $PILOT AppRole -> $(basename "$ENV_FILE") (role_id ${ROLE_PREFIX}..., secret_id masked, mode 600)"
