#!/usr/bin/env python3
"""The documentation tree: what can be reached from README.md, and what cannot.

THE PROBLEM THIS SOLVES.

This repository documents itself heavily, and README.md is declared to be the
single index. Both of those are only useful together: a document nothing links
to is not documentation, it is a file. Nobody opens it, nobody notices when it
goes stale, and the next person writes a second copy of it because they could
not find the first -- which is how a repository ends up with two conflicting
descriptions of the same subsystem and no way to tell which one is current.

So this walks the actual link graph from README.md outward and answers three
questions that cannot be answered by reading any single file:

  reachable    a person starting at the index can arrive here by clicking
  ORPHAN       tracked, written, and reachable from nothing
  BROKEN       linked from somewhere, but the target does not exist

An orphan is not automatically a defect -- some files are legitimately not part
of the reading tree. But every one has to be a DECISION, recorded in EXEMPT
below with the reason, rather than an accident nobody noticed.

WHY LINKS AND NOT A HAND-MAINTAINED MANIFEST.

A manifest is a second thing to update, so it rots the first time somebody adds
a document in a hurry -- and a stale manifest reports full coverage of a tree
that has grown. Walking the real links means a new unlinked document shows up
as an orphan on the next run without anyone remembering to do anything.

WHAT THIS CANNOT PROVE, WHICH MATTERS AS MUCH AS WHAT IT CAN.

Reachability is not currency. The document that did the most damage in this
repository -- a hand-curated status page declaring "data governance and process
visualisation are almost empty" nine days after both were built -- was
reachable, prominently linked, and labelled "read this first". This walk would
have given it a clean bill of health, because it was clean: it was linked.

So --tree exists to make the graph usable for MAINTENANCE rather than only as a
gate. It prints the tree a reader actually descends, annotated with how long
since each document was last touched, so the question "which part of this tree
has nobody looked at" has an answer that does not depend on remembering. The
complementary question -- "is this document generated, or is somebody promising
to keep it true by hand" -- is `platform/docs/doc_freshness.py`.

Usage:
  doc_graph.py             human-readable report
  doc_graph.py --tree      the reading tree, annotated with age
  doc_graph.py --json      machine-readable
  doc_graph.py --check     exit 1 if there are unexplained orphans or broken links

Exit codes:
  0  every tracked document is reachable or explicitly exempt, no broken links
  1  --check found unexplained orphans, or broken links
  2  the walk found fewer documents than the floor -- refusing to report
"""

import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
ROOT_DOC = "README.md"

# A tree this size cannot collapse to a handful of documents by accident. If the
# walk returns fewer than this, the link parser has broken and the honest output
# is an error -- "0 orphans out of 3 documents reached" is the shape of a clean
# bill of health derived from having looked at almost nothing.
MIN_REACHED = 20

# Documents deliberately outside the reading tree. Each needs a reason, and the
# reason is the point: an exemption without one is indistinguishable from an
# oversight that somebody silenced.
EXEMPT = {
    "docs/decisions/index.md":
        "generated by platform/docs/decisions.py; linked as a directory index, "
        "and regenerating it is what keeps it correct",
    "evidence/_retired/README.md":
        "explains the retirement convention to whoever opens that directory; "
        "it is reached by browsing evidence/, not by reading the index",
    "pilots/station2-twin/ingest/certs/README.md":
        "a note in a certificate directory telling you not to commit keys there; "
        "it belongs next to the thing it warns about, not in the reading tree",
}


def tracked_docs():
    out = subprocess.run(
        ["git", "-C", REPO_ROOT, "ls-files", "*.md"],
        capture_output=True, text=True, check=False,
    ).stdout
    return sorted(p for p in out.splitlines() if p)


# Markdown links plus the HTML hrefs that appear in the few generated pages.
# Bare URLs are ignored on purpose: this walks the FILE tree, and an http link
# is checked by test_readme_index.sh, which can actually fetch it.
LINK_RE = re.compile(r"\[[^\]]*\]\(([^)]+)\)|href=\"([^\"]+)\"")


def links_from(path):
    """Every repo-relative path this document links to."""
    full = os.path.join(REPO_ROOT, path)
    try:
        with open(full, "r") as handle:
            text = handle.read()
    except (OSError, UnicodeDecodeError):
        return []

    base = os.path.dirname(path)
    found = []
    for match in LINK_RE.finditer(text):
        target = match.group(1) or match.group(2) or ""
        target = target.strip().split()[0] if target.strip() else ""
        if not target:
            continue
        # Absolute URLs, anchors and mailto are not file links.
        if re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*:", target) or target.startswith("#"):
            continue
        target = target.split("#", 1)[0]
        if not target:
            continue
        resolved = os.path.normpath(os.path.join(base, target)) if base else os.path.normpath(target)
        found.append((target, resolved))
    return found


def walk():
    docs = set(tracked_docs())
    tracked_any = set(
        subprocess.run(["git", "-C", REPO_ROOT, "ls-files"],
                       capture_output=True, text=True, check=False).stdout.splitlines()
    )

    reached = set()
    broken = []          # (source, raw target)
    children = {}        # first discoverer -> documents it introduced
    queue = [ROOT_DOC]
    reached.add(ROOT_DOC)

    while queue:
        current = queue.pop(0)   # breadth-first, so a document's parent in the
                                 # rendered tree is its SHALLOWEST route in
        for raw, resolved in links_from(current):
            exists = (
                resolved in tracked_any
                or os.path.exists(os.path.join(REPO_ROOT, resolved))
            )
            if not exists:
                # A link to a generated artifact that is gitignored is not
                # broken -- it is a build output. test_readme_index.sh draws
                # the same distinction for the same reason.
                ignored = subprocess.run(
                    ["git", "-C", REPO_ROOT, "check-ignore", "-q", resolved],
                    capture_output=True, check=False,
                ).returncode == 0
                if not ignored:
                    broken.append((current, raw))
                continue
            if resolved.endswith(".md") and resolved in docs and resolved not in reached:
                reached.add(resolved)
                children.setdefault(current, []).append(resolved)
                queue.append(resolved)

    orphans = sorted(docs - reached - set(EXEMPT))
    exempt_present = sorted(set(EXEMPT) & docs)
    exempt_stale = sorted(set(EXEMPT) - docs)
    return {
        "root": ROOT_DOC,
        "tracked": len(docs),
        "reached": len(reached & docs),
        "orphans": orphans,
        "exempt": exempt_present,
        "exempt_stale": exempt_stale,
        "broken": [{"in": s, "link": t} for s, t in sorted(broken)],
        "children": {k: sorted(v) for k, v in children.items()},
    }


def last_touched_days():
    """Days since each tracked file was last committed.

    One `git log` over the whole history rather than one per file: 60-odd
    subprocesses to answer a question this cheap is how a useful report turns
    into one nobody waits for.
    """
    out = subprocess.run(
        ["git", "-C", REPO_ROOT, "log", "--format=@%ct", "--name-only", "--no-renames"],
        capture_output=True, text=True, check=False).stdout
    now = int(subprocess.run(["date", "+%s"], capture_output=True, text=True,
                             check=False).stdout.strip() or 0)
    ages, stamp = {}, None
    for line in out.splitlines():
        if line.startswith("@"):
            stamp = int(line[1:])
        elif line.strip() and stamp is not None and line not in ages:
            ages[line] = max(0, (now - stamp) // 86400)
    return ages


def render_tree(report):
    """The tree a reader descends, with the age of every document on it."""
    ages = last_touched_days()
    children = report["children"]
    printed = set()

    def walk_node(path, prefix, is_last, depth):
        if depth > 12:
            return
        age = ages.get(path)
        mark = "" if age is None else ("%4dd" % age)
        # A document reachable by two routes is shown once, at its shallowest,
        # and marked elsewhere -- otherwise the tree prints the same subtree
        # repeatedly and stops being readable, which defeats the purpose.
        if path in printed:
            print("%s%s%s  (already above)" % (prefix, "`-- " if is_last else "|-- ", path))
            return
        printed.add(path)
        print("%s%s%-58s %s" % (prefix, "" if depth == 0 else ("`-- " if is_last else "|-- "),
                                path, mark))
        kids = children.get(path, [])
        nxt = prefix if depth == 0 else prefix + ("    " if is_last else "|   ")
        for i, kid in enumerate(kids):
            walk_node(kid, nxt, i == len(kids) - 1, depth + 1)

    print("reading tree from %s   (right column: days since last commit)" % ROOT_DOC)
    walk_node(ROOT_DOC, "", True, 0)

    stale = sorted(((ages.get(p, 0), p) for p in printed if ages.get(p) is not None),
                   reverse=True)[:8]
    if stale:
        print()
        print("longest untouched on the tree:")
        for age, path in stale:
            print("  %4dd  %s" % (age, path))
        print()
        print("  Age is not a defect. It is the only cheap signal for WHERE to look,")
        print("  and whether a document may go stale at all depends on whether")
        print("  anything regenerates it -- see platform/docs/doc_freshness.py.")


def main(argv):
    as_json = "--json" in argv
    check = "--check" in argv
    as_tree = "--tree" in argv

    report = walk()

    if report["reached"] < MIN_REACHED:
        sys.stderr.write(
            "REFUSED: reached only %d document(s) from %s, expected at least %d.\n"
            "  The link parser is not finding links any more. Reporting '0 orphans'\n"
            "  from a walk that visited almost nothing is the exact failure this\n"
            "  file exists to prevent.\n" % (report["reached"], ROOT_DOC, MIN_REACHED)
        )
        return 2

    if as_tree:
        render_tree(report)
    elif as_json:
        print(json.dumps(report, indent=2, ensure_ascii=False))
    else:
        print("documentation tree from %s" % ROOT_DOC)
        print("  %d of %d tracked documents reachable by clicking"
              % (report["reached"], report["tracked"]))
        if report["exempt"]:
            print("  %d exempt (deliberately outside the tree):" % len(report["exempt"]))
            for path in report["exempt"]:
                print("      %-46s %s" % (path, EXEMPT[path]))
        if report["exempt_stale"]:
            print("  STALE EXEMPTIONS (file no longer exists -- delete the entry):")
            for path in report["exempt_stale"]:
                print("      %s" % path)
        if report["broken"]:
            print("  BROKEN LINKS:")
            for item in report["broken"]:
                print("      %-46s -> %s" % (item["in"], item["link"]))
        if report["orphans"]:
            print("  ORPHANS (tracked, written, reachable from nothing):")
            for path in report["orphans"]:
                print("      %s" % path)
        if not report["orphans"] and not report["broken"] and not report["exempt_stale"]:
            print("  no orphans, no broken links, no stale exemptions")

    if check:
        bad = len(report["orphans"]) + len(report["broken"]) + len(report["exempt_stale"])
        return 1 if bad else 0
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
