#!/usr/bin/env python3
"""Aggregate the health probe's per-run snapshots into one queryable answer.

WHY THIS EXISTS
---------------
`check_health.sh` writes one `evidence/observability/health_<ts>.json` every 15
minutes.  After three weeks that is ~1,500 structurally identical files.
ADR-0006 measured this pile and drew the conclusion that matters:

    "沒有任何 agent 會讀 1,215 個檔。它會讀一兩個然後外推 --
     而「讀了兩個就結論全體健康」正是 grounding gap 的定義，
     只是穿著證據的外衣。"

and then named the remedy explicitly:

    "收斂要用彙總，不是用 `find -mtime -delete`。"
    "同構的時間序列證據應該可查詢，不是可堆積。"

So this script does NOT delete anything.  Deleting old snapshots would destroy
traceability, which is the entire point of `evidence/`.  It reads every
snapshot and answers, in one artifact, the questions nobody can answer by
opening two files at random:

  * over the whole recorded history, how often was each integrity check NOT ok?
  * were the failures scattered noise, or one long unbroken episode?
  * did the probe itself stop -- are there holes where NO evidence was written?

That last question is the important one, and it is invisible in any single
snapshot.  A snapshot can only say what was true when it was written.  A gap
says nobody was watching, and a gap looks byte-identical to "nothing happened"
unless something explicitly counts the missing intervals.  This is the same
failure shape the platform already guards against elsewhere: a dead monitor
reports zero alerts, which reads exactly like health.

WHAT IT REFUSES TO DO
---------------------
It exits non-zero and writes NO metrics file when it finds zero snapshots.
"Every check passed" over an empty set is vacuously true, and a green textfile
produced from nothing is worse than no textfile -- Prometheus would carry it
forward and the board would report calm.  VACUOUS is not PASS.

OUTPUTS
-------
  evidence/observability/health_rollup.json   schema health-rollup/1
  evidence/statusdag/health_rollup.prom       Prometheus textfile collector

The .prom lands in the directory node-exporter already mounts read-only
(see platform/observability/compose.yaml), so the aggregate becomes visible on
the board without a new scrape target.

Usage:
  python3 platform/observability/rollup_health.py [--json] [--no-write]

Exit codes:
  0  rollup written
  1  no snapshots found -- refused to write a vacuous result
  2  snapshots found but unparseable
"""

import glob
import json
import os
import sys
from datetime import datetime, timezone

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Overridable so the test suite can feed synthetic snapshot sets -- a control
# that fabricates a 6-hour outage and checks this script reports it is the only
# way to know the detector still detects.  Reading the real evidence directory
# proves nothing: it is expected to be mostly clean, so a detector that always
# returned "no episodes" would pass against it every time.
SNAPSHOT_DIR = os.environ.get("HEALTH_SNAPSHOT_DIR") or os.path.join(
    REPO_ROOT, "evidence", "observability"
)
ROLLUP_JSON = os.environ.get("HEALTH_ROLLUP_JSON") or os.path.join(
    SNAPSHOT_DIR, "health_rollup.json"
)
TEXTFILE = os.environ.get("HEALTH_ROLLUP_PROM") or os.path.join(
    REPO_ROOT, "evidence", "statusdag", "health_rollup.prom"
)

# The scheduled cadence of the health job (platform/scheduler/jobs.conf).  A
# gap longer than GAP_FACTOR x this means the probe missed at least one run:
# the laptop slept, the agent was uninstalled, or the job hung holding its
# lock.  2.5x rather than 2x so that ordinary scheduler jitter and a single
# slow run do not get reported as an outage of the monitoring itself.
NOMINAL_INTERVAL_S = 900
GAP_FACTOR = 2.5


def parse_ts(value):
    """Parse the ISO-8601 Zulu timestamps check_health.py writes."""
    if not value:
        return None
    try:
        return datetime.strptime(value, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
    except ValueError:
        return None


def load_snapshots(directory):
    """Read every health_<ts>.json, ordered by the time it claims to describe.

    Sorting by `checked_at` rather than by filename is deliberate: the filename
    is generated by the writer, but the field is what the probe asserts about
    the world, and gap detection is only meaningful against the asserted time.
    Files that parse but carry no usable timestamp are counted separately --
    they are not silently dropped, because a snapshot that cannot be placed in
    time is itself a defect worth surfacing.
    """
    snapshots = []
    undated = 0
    unreadable = 0
    for path in sorted(glob.glob(os.path.join(directory, "health_*.json"))):
        if os.path.basename(path) == "health_rollup.json":
            continue
        try:
            with open(path, "r") as handle:
                doc = json.load(handle)
        except (ValueError, OSError):
            unreadable += 1
            continue
        when = parse_ts(doc.get("checked_at"))
        if when is None:
            undated += 1
            continue
        snapshots.append((when, doc))
    snapshots.sort(key=lambda item: item[0])
    return snapshots, undated, unreadable


def find_episodes(snapshots):
    """Collapse consecutive not-ok runs of the same check into one episode.

    Counting individual bad samples answers "how noisy was it".  Counting
    episodes answers "how long was it broken and nobody acted", which is the
    question an incident review actually asks.  ADR-0006 records the case that
    motivated this: an alert rule that failed EVERY evaluation cycle for 11
    unbroken hours while the board showed `prometheus ok`.  As 44 scattered
    samples that reads like flapping; as one 11-hour episode it reads like
    what it was.
    """
    open_episodes = {}
    closed = []

    def close(check, last_seen):
        started, count = open_episodes.pop(check)
        closed.append(
            {
                "check": check,
                "from": started.strftime("%Y-%m-%dT%H:%M:%SZ"),
                "to": last_seen.strftime("%Y-%m-%dT%H:%M:%SZ"),
                "duration_s": int((last_seen - started).total_seconds()),
                "samples": count,
            }
        )

    previous = None
    for when, doc in snapshots:
        failing = set()
        for entry in doc.get("monitoring_integrity") or []:
            if not entry.get("ok"):
                failing.add(entry.get("check") or "unnamed")
        if doc.get("verdict") not in ("HEALTHY", None):
            failing.add("verdict:" + str(doc.get("verdict")))

        for check in list(open_episodes):
            if check not in failing:
                close(check, previous if previous is not None else when)
        for check in failing:
            if check not in open_episodes:
                open_episodes[check] = (when, 0)
            started, count = open_episodes[check]
            open_episodes[check] = (started, count + 1)
        previous = when

    for check in list(open_episodes):
        close(check, previous)
    closed.sort(key=lambda e: e["duration_s"], reverse=True)
    return closed


def find_gaps(snapshots):
    """Intervals where no snapshot was written at all.

    A gap is not a health finding -- it is the absence of one.  It is reported
    separately from failures for that reason: "we looked and it was broken" and
    "we never looked" must not be summed into a single number, because only the
    first is evidence.
    """
    gaps = []
    threshold = NOMINAL_INTERVAL_S * GAP_FACTOR
    for index in range(1, len(snapshots)):
        previous = snapshots[index - 1][0]
        current = snapshots[index][0]
        delta = (current - previous).total_seconds()
        if delta > threshold:
            gaps.append(
                {
                    "from": previous.strftime("%Y-%m-%dT%H:%M:%SZ"),
                    "to": current.strftime("%Y-%m-%dT%H:%M:%SZ"),
                    "duration_s": int(delta),
                    "missed_runs": int(delta // NOMINAL_INTERVAL_S) - 1,
                }
            )
    gaps.sort(key=lambda g: g["duration_s"], reverse=True)
    return gaps


def build(snapshots, undated, unreadable):
    verdicts = {}
    checks = {}
    for _, doc in snapshots:
        verdict = doc.get("verdict") or "MISSING"
        verdicts[verdict] = verdicts.get(verdict, 0) + 1
        for entry in doc.get("monitoring_integrity") or []:
            name = entry.get("check") or "unnamed"
            row = checks.setdefault(name, {"observed": 0, "failed": 0})
            row["observed"] += 1
            if not entry.get("ok"):
                row["failed"] += 1

    episodes = find_episodes(snapshots)
    gaps = find_gaps(snapshots)
    first = snapshots[0][0]
    last = snapshots[-1][0]
    span = (last - first).total_seconds()

    # Expected sample count over the span, used to state coverage as a
    # fraction.  Reported rather than asserted: the correct value depends on
    # when the scheduler was installed, which this script cannot know.
    expected = int(span // NOMINAL_INTERVAL_S) + 1 if span > 0 else 1

    return {
        "schema": "health-rollup/1",
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "source_dir": "evidence/observability",
        "snapshots": len(snapshots),
        "snapshots_undated": undated,
        "snapshots_unreadable": unreadable,
        "first_sample": first.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "last_sample": last.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "span_s": int(span),
        "expected_samples": expected,
        "coverage_ratio": round(len(snapshots) / expected, 4) if expected else 0.0,
        "verdicts": verdicts,
        "checks": checks,
        "episodes": episodes,
        "coverage_gaps": gaps,
    }


def render_prom(rollup):
    def esc(value):
        return str(value).replace("\\", "\\\\").replace('"', '\\"')

    lines = [
        "# Aggregate of every evidence/observability/health_*.json.",
        "# Written by platform/observability/rollup_health.py -- see that file",
        "# for why this exists rather than a retention policy.",
        "# HELP devops_health_rollup_snapshots_total Health snapshots aggregated.",
        "# TYPE devops_health_rollup_snapshots_total gauge",
        "devops_health_rollup_snapshots_total %d" % rollup["snapshots"],
        "# HELP devops_health_rollup_generated_seconds Unix time the rollup was built.",
        "# TYPE devops_health_rollup_generated_seconds gauge",
        "devops_health_rollup_generated_seconds %d"
        % int(parse_ts(rollup["generated_at"]).timestamp()),
        "# HELP devops_health_rollup_coverage_ratio Snapshots present divided by snapshots expected across the recorded span.",
        "# TYPE devops_health_rollup_coverage_ratio gauge",
        "devops_health_rollup_coverage_ratio %s" % rollup["coverage_ratio"],
        "# HELP devops_health_verdict_samples_total Snapshots recording each verdict.",
        "# TYPE devops_health_verdict_samples_total gauge",
    ]
    for verdict in sorted(rollup["verdicts"]):
        lines.append(
            'devops_health_verdict_samples_total{verdict="%s"} %d'
            % (esc(verdict), rollup["verdicts"][verdict])
        )

    lines += [
        "# HELP devops_health_check_failed_total Snapshots in which an integrity check was not ok.",
        "# TYPE devops_health_check_failed_total gauge",
    ]
    for check in sorted(rollup["checks"]):
        lines.append(
            'devops_health_check_failed_total{check="%s"} %d'
            % (esc(check), rollup["checks"][check]["failed"])
        )

    # Longest unbroken episode per check.  The maximum, not the sum: an hour of
    # continuous breakage and four scattered quarter-hours sum alike, and only
    # the first is an outage.
    longest = {}
    for episode in rollup["episodes"]:
        name = episode["check"]
        longest[name] = max(longest.get(name, 0), episode["duration_s"])
    lines += [
        "# HELP devops_health_longest_episode_seconds Longest unbroken run of consecutive not-ok snapshots.",
        "# TYPE devops_health_longest_episode_seconds gauge",
    ]
    for check in sorted(longest):
        lines.append(
            'devops_health_longest_episode_seconds{check="%s"} %d' % (esc(check), longest[check])
        )

    gaps = rollup["coverage_gaps"]
    lines += [
        "# HELP devops_health_coverage_gaps_total Intervals in which no snapshot was written at all.",
        "# TYPE devops_health_coverage_gaps_total gauge",
        "devops_health_coverage_gaps_total %d" % len(gaps),
        "# HELP devops_health_coverage_gap_longest_seconds Longest interval with no snapshot.",
        "# TYPE devops_health_coverage_gap_longest_seconds gauge",
        "devops_health_coverage_gap_longest_seconds %d" % (gaps[0]["duration_s"] if gaps else 0),
    ]
    return "\n".join(lines) + "\n"


def write_atomic(path, content):
    """Write via a temp file in the same directory, then rename.

    node-exporter reads this directory on its own schedule.  A partially
    written .prom file is a parse error at the collector, which surfaces as
    the metric vanishing -- indistinguishable from the platform being fine.
    """
    tmp = path + ".tmp"
    with open(tmp, "w") as handle:
        handle.write(content)
    os.replace(tmp, path)


def main(argv):
    as_json = "--json" in argv
    write = "--no-write" not in argv

    snapshots, undated, unreadable = load_snapshots(SNAPSHOT_DIR)

    if not snapshots:
        sys.stderr.write(
            "REFUSED: no dated snapshots in %s\n"
            "  A rollup over zero samples would report every check clean.\n"
            "  That is vacuous, not healthy -- writing no metrics instead.\n"
            % SNAPSHOT_DIR
        )
        return 2 if unreadable else 1

    rollup = build(snapshots, undated, unreadable)

    if write:
        write_atomic(ROLLUP_JSON, json.dumps(rollup, indent=2, sort_keys=False) + "\n")
        write_atomic(TEXTFILE, render_prom(rollup))

    if as_json:
        print(json.dumps(rollup, indent=2))
        return 0

    print("health rollup  %s .. %s" % (rollup["first_sample"], rollup["last_sample"]))
    print(
        "  snapshots %d   coverage %.1f%% of %d expected"
        % (rollup["snapshots"], rollup["coverage_ratio"] * 100, rollup["expected_samples"])
    )
    if undated or unreadable:
        print("  undated %d   unreadable %d" % (undated, unreadable))
    print("  verdicts: " + ", ".join("%s=%d" % kv for kv in sorted(rollup["verdicts"].items())))
    for check in sorted(rollup["checks"]):
        row = rollup["checks"][check]
        if row["failed"]:
            print("  FAILED %-28s %d/%d snapshots" % (check, row["failed"], row["observed"]))
    if rollup["episodes"]:
        print("  longest episodes:")
        for episode in rollup["episodes"][:5]:
            print(
                "    %-28s %6.1fh  %s -> %s"
                % (
                    episode["check"],
                    episode["duration_s"] / 3600.0,
                    episode["from"],
                    episode["to"],
                )
            )
    if rollup["coverage_gaps"]:
        print("  coverage gaps (nobody was watching):")
        for gap in rollup["coverage_gaps"][:5]:
            print(
                "    %6.1fh  %s -> %s  (%d missed runs)"
                % (
                    gap["duration_s"] / 3600.0,
                    gap["from"],
                    gap["to"],
                    gap["missed_runs"],
                )
            )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
