global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: station1-hello
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:18080"]
        labels:
          environment: develop
          service: station1-hello
